development:
  adapter: mysql2
  database: codesnipet_development
  username: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: codesnipet_test
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: codesnipet
  host: codesnipet.c6qfs9f7d633.us-west-2.rds.amazonaws.com
  username: admin
  password: PUNKETO!
  port: 3306
  pool: 5
  timeout: 5000
